name: Docker Build and Push Frontend

on:
  push:
    branches: [ "develop", "homolog" ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/frontend
  NODE_VERSION: 20.x

defaults:
  run:
    working-directory: ./frontend

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Update Global Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: 'frontend/yarn.lock'

#      - name: Prettier
#        id: prettier
#        run: npx prettier@3.0.3 --single-quote --check 'src/**/*.{js,jsx,ts,tsx,css,scss}' --config=package.json
#
      - name: Install packages
        run: make install
#
#      - name: ESLint
#        id: eslint
#        if: ${{ success() || failure() }}
#        run: yarn run lint:ci
#
#      - name: i18n sync
#        id: i18n
#        if: ${{ success() || failure() }}
#        run: make i18n-ci
#
#      - name: Unit Tests
#        id: unit
#        if: ${{ success() || failure() }}
#        run: make test
#
#      - name: Report
#        if: ${{ success() || failure() }}
#        run: |
#          echo '# Code Analysis' >> $GITHUB_STEP_SUMMARY
##          echo '| Test | Status |' >> $GITHUB_STEP_SUMMARY
#          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
##          echo '| Prettier | ${{ steps.prettier.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
##          echo '| ESLint | ${{ steps.eslint.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
##          echo '| i18n | ${{ steps.i18n.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY
#          echo '| Unit Tests | ${{ steps.unit.conclusion == 'failure' && '❌' || ' ✅' }} |' >> $GITHUB_STEP_SUMMARY

  build-and-push:
    runs-on: ubuntu-latest
    needs:
      - code-analysis
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag based on branch
        id: image-tag
        run: |
          if [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            echo "tag=dev" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "homolog" ]]; then
            echo "tag=homolog" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          fi

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.image-tag.outputs.tag }}
            type=raw,value=${{ needs.version.outputs.version }}
          labels: |
            org.label-schema.docker.cmd=docker run -d -p 3000:3000 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image-tag.outputs.tag }}

      - name: Build and push Docker image
        if: contains(github.ref, 'homolog')
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          context: frontend
          file: frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
