name: Release Backend

on:
  push:
    branches:
      - develop
      - homolog
      - main
  pull_request:
    types:
      - closed
    branches:
      - develop
      - homolog
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event.pull_request.merged == true || github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install python-semantic-release
        run: pip install python-semantic-release

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
        working-directory: ./backend/src/camara_de_curitiba

  build-image:
    needs: release
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/homolog' || github.ref == 'refs/heads/main') && (github.event.action == 'closed' && github.event.pull_request.merged == true || github.event_name == 'push')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from setup.py
        id: backend-version
        working-directory: ./backend/src/camara_de_curitiba
        run: |
          echo "version=$(python3 setup.py --version)" >> $GITHUB_OUTPUT

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/cmcuritiba/portal/backend:${{ steps.backend-version.outputs.version }}
            ghcr.io/cmcuritiba/portal/backend:${{ github.sha }}
            ghcr.io/cmcuritiba/portal/backend:${{ github.ref_name }}
          labels: |
            org.opencontainers.image.version=${{ steps.backend-version.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 