name: Release Backend

on:
  push:
    branches:
      - develop
      - homolog
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/src/camara_de_curitiba
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release[all]

      - name: Run python-semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release publish

  build-image:
    needs: release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/homolog' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.REGISTRY }}/backend:${{ github.sha }}
            ${{ secrets.REGISTRY }}/backend:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 