name: Bump Version and Update Changelog for Backend

on:
  push:
    branches:
      - develop
      - homolog
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install setuptools

      - name: Bump version in setup.py
        run: |
          branch_name=$(echo "${GITHUB_REF}" | sed 's|refs/heads/||')
          if [[ "$branch_name" == "develop" ]]; then
            version_suffix="-dev"
          elif [[ "$branch_name" == "homolog" ]]; then
            version_suffix="-rc"
          elif [[ "$branch_name" == "main" ]]; then
            version_suffix=""
          fi
          current_version=$(grep "version=" backend/src/camara_de_curitiba/setup.py | sed -E 's/.*version="([^"]+)".*/\1/')
          new_version=$(python -c "import semantic_version; print(semantic_version.Version('$current_version').next_patch())")
          sed -i "s/version=\"$current_version\"/version=\"$new_version$version_suffix\"/" backend/src/camara_de_curitiba/setup.py

      - name: Update CHANGELOG.md
        run: |
          git log $(git describe --tags --abbrev=0)..HEAD --oneline > backend/CHANGELOG.md

      - name: Commit version bump and changelog
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add backend/src/camara_de_curitiba/setup.py backend/CHANGELOG.md
          git commit -m "Bump backend version and update changelog"
          git push

  draft-release:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Draft release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: backend-release-drafter.yml
